---
title: "t-SNE plot"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
    
    
params:
  sampleID: "U583"
  pipeline: "/data/Compass/dev/nagarajs2/classifier_pipeline/"
  out_path: "NULL"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,echo=FALSE,error=FALSE,message=FALSE,warning=FALSE, fig.height=15, fig.width=15}
library(plotly)
#setwd("~/Desktop/methyl_array_analysis/tSNE")
anno <- read.table(file.path(params$pipeline, "/scripts/classifier/plotting/GSE90496_pData.txt"), header = T, sep = "\t")
mclass <- anno$methylation.class.ch1
mclass <- as.character(mclass)
mclass[2802] <- params$sampleID
my_symbols <- c(rep("1", 2801), "2")
dat <- read.table(file = file.path(params$out_path, paste0(params$sampleID, "_tSNE.txt")), header = T)
y <- read.table(file = file.path(params$pipeline, "/scripts/classifier/plotting/methylation_class_to_color_mapping.txt"), header = T, as.is = c(1,2,3), sep = "\t")
y <- rbind(y, c("grey0", params$sampleID, "unknown"))
pal <- y$Color
pal <- setNames(pal, y$Class)

dat1 <- cbind(dat, mclass, my_symbols)

ann_coord <- vector("list", length(y$Class))
names(ann_coord) <- y$Class
for( c in y$Class ){
  ann_coord[[c]] <- head(dat1[mclass == c,], 1) 
}
cluster_annotations <- do.call(rbind, ann_coord)
p <- plot_ly(dat1, x = ~V1, y = ~V2, z = ~V3, color = ~mclass, colors = pal, symbol = ~my_symbols, symbols = c("circle", "square")) %>% add_trace(type = "scatter3d", mode = "markers", marker = list(size = 4), opacity = 0.5, text = mclass, hoverinfo = "text", showlegend = FALSE) %>% add_trace(x = dat1[2802, 1], y = dat1[2802, 2], z = dat1[2802, 3], type = "scatter3d", mode = "markers", marker = list(size = 9, color = "#0000FF", symbol = "circle"), text = mclass[2802], hoverinfo = "text", showlegend = FALSE) %>% layout(scene = list(camera = list(center = list(x = 0, y = 0, z = 0), eye = list(x = 1.25, y = 1.25, z = 1.25), up = list(x = 0, y = 0, z = 1)), annotations = list(list(x = cluster_annotations[92, 1], y = cluster_annotations[92, 2], z = cluster_annotations[92, 3], text = sprintf("<b>%s</b>", cluster_annotations[92, 4]), font = list(size = 14, color = "#FFFFFF"), ax = 0, ay = -75, standoff = 1, arrowsize = 3, arrowwidth = 2, arrowhead = 3, arrowcolor = "#FF3300", bordercolor = "#FF3300", borderpad = 2, bgcolor = "#FF7F0E"), list(showarrow = F, x = cluster_annotations[1, 1], y = cluster_annotations[1, 2], z = cluster_annotations[1, 3], text = sprintf("<b>%s</b>",cluster_annotations[1, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[2, 1], y = cluster_annotations[2, 2], z = cluster_annotations[2, 3], text = sprintf("<b>%s</b>", cluster_annotations[2, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[3, 1], y = cluster_annotations[3, 2], z = cluster_annotations[3, 3], text = sprintf("<b>%s</b>", cluster_annotations[3, 4]), font = list(size = 11)), 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        list(showarrow = F, x = cluster_annotations[4, 1], y = cluster_annotations[4, 2], z = cluster_annotations[4, 3], text = sprintf("<b>%s</b>", cluster_annotations[4, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[5, 1], y = cluster_annotations[5, 2], z = cluster_annotations[5, 3], text = sprintf("<b>%s</b>", cluster_annotations[5, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[6, 1], y = cluster_annotations[6, 2], z = cluster_annotations[6, 3], text = sprintf("<b>%s</b>", cluster_annotations[6, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[7, 1], y = cluster_annotations[7, 2], z = cluster_annotations[7, 3], text = sprintf("<b>%s</b>", cluster_annotations[7, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[8, 1], y = cluster_annotations[8, 2], z = cluster_annotations[8, 3], text = sprintf("<b>%s</b>", cluster_annotations[8, 4]), font = list(size = 11)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        list(showarrow = F, x = cluster_annotations[9, 1], y = cluster_annotations[9, 2], z = cluster_annotations[9, 3], text = sprintf("<b>%s</b>", cluster_annotations[9, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[10, 1], y = cluster_annotations[10, 2], z = cluster_annotations[10, 3], text = sprintf("<b>%s</b>", cluster_annotations[10, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[11, 1], y = cluster_annotations[11, 2], z = cluster_annotations[11, 3], text = sprintf("<b>%s</b>", cluster_annotations[11, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[12, 1], y = cluster_annotations[12, 2], z = cluster_annotations[12, 3], text = sprintf("<b>%s</b>", cluster_annotations[12, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[13, 1], y = cluster_annotations[13, 2], z = cluster_annotations[13, 3], text = sprintf("<b>%s</b>", cluster_annotations[13, 4]), font = list(size = 11)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        list(showarrow = F, x = cluster_annotations[14, 1], y = cluster_annotations[14, 2], z = cluster_annotations[14, 3], text = sprintf("<b>%s</b>", cluster_annotations[14, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[15, 1], y = cluster_annotations[15, 2], z = cluster_annotations[15, 3], text = sprintf("<b>%s</b>", cluster_annotations[15, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[16, 1], y = cluster_annotations[16, 2], z = cluster_annotations[16, 3], text = sprintf("<b>%s</b>", cluster_annotations[16, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[17, 1], y = cluster_annotations[17, 2], z = cluster_annotations[17, 3], text = sprintf("<b>%s</b>", cluster_annotations[17, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[18, 1], y = cluster_annotations[18, 2], z = cluster_annotations[18, 3], text = sprintf("<b>%s</b>", cluster_annotations[18, 4]), font = list(size = 11)), 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        list(showarrow = F, x = cluster_annotations[19, 1], y = cluster_annotations[19, 2], z = cluster_annotations[19, 3], text = sprintf("<b>%s</b>", cluster_annotations[19, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[20, 1], y = cluster_annotations[20, 2], z = cluster_annotations[20, 3], text = sprintf("<b>%s</b>", cluster_annotations[20, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[21, 1], y = cluster_annotations[21, 2], z = cluster_annotations[21, 3], text = sprintf("<b>%s</b>", cluster_annotations[21, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[22, 1], y = cluster_annotations[22, 2], z = cluster_annotations[22, 3], text = sprintf("<b>%s</b>", cluster_annotations[22, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[23, 1], y = cluster_annotations[23, 2], z = cluster_annotations[23, 3], text = sprintf("<b>%s</b>", cluster_annotations[23, 4]), font = list(size = 11)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        list(showarrow = F, x = cluster_annotations[24, 1], y = cluster_annotations[24, 2], z = cluster_annotations[24, 3], text = sprintf("<b>%s</b>", cluster_annotations[24, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[25, 1], y = cluster_annotations[25, 2], z = cluster_annotations[25, 3], text = sprintf("<b>%s</b>", cluster_annotations[25, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[26, 1], y = cluster_annotations[26, 2], z = cluster_annotations[26, 3], text = sprintf("<b>%s</b>", cluster_annotations[26, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[27, 1], y = cluster_annotations[27, 2], z = cluster_annotations[27, 3], text = sprintf("<b>%s</b>", cluster_annotations[27, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[28, 1], y = cluster_annotations[28, 2], z = cluster_annotations[28, 3], text = sprintf("<b>%s</b>", cluster_annotations[28, 4]), font = list(size = 11)), 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        list(showarrow = F, x = cluster_annotations[29, 1], y = cluster_annotations[29, 2], z = cluster_annotations[29, 3], text = sprintf("<b>%s</b>", cluster_annotations[29, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[30, 1], y = cluster_annotations[30, 2], z = cluster_annotations[30, 3], text = sprintf("<b>%s</b>", cluster_annotations[30, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[31, 1], y = cluster_annotations[31, 2], z = cluster_annotations[31, 3], text = sprintf("<b>%s</b>", cluster_annotations[31, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[32, 1], y = cluster_annotations[32, 2], z = cluster_annotations[32, 3], text = sprintf("<b>%s</b>", cluster_annotations[32, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[33, 1], y = cluster_annotations[33, 2], z = cluster_annotations[33, 3], text = sprintf("<b>%s</b>", cluster_annotations[33, 4]), font = list(size = 11)), 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        list(showarrow = F, x = cluster_annotations[34, 1], y = cluster_annotations[34, 2], z = cluster_annotations[34, 3], text = sprintf("<b>%s</b>", cluster_annotations[34, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[35, 1], y = cluster_annotations[35, 2], z = cluster_annotations[35, 3], text = sprintf("<b>%s</b>", cluster_annotations[35, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[36, 1], y = cluster_annotations[36, 2], z = cluster_annotations[36, 3], text = sprintf("<b>%s</b>", cluster_annotations[36, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[37, 1], y = cluster_annotations[37, 2], z = cluster_annotations[37, 3], text = sprintf("<b>%s</b>", cluster_annotations[37, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[38, 1], y = cluster_annotations[38, 2], z = cluster_annotations[38, 3], text = sprintf("<b>%s</b>", cluster_annotations[38, 4]), font = list(size = 11)), 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        list(showarrow = F, x = cluster_annotations[39, 1], y = cluster_annotations[39, 2], z = cluster_annotations[39, 3], text = sprintf("<b>%s</b>", cluster_annotations[39, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[40, 1], y = cluster_annotations[40, 2], z = cluster_annotations[40, 3], text = sprintf("<b>%s</b>", cluster_annotations[40, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[41, 1], y = cluster_annotations[41, 2], z = cluster_annotations[41, 3], text = sprintf("<b>%s</b>", cluster_annotations[41, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[42, 1], y = cluster_annotations[42, 2], z = cluster_annotations[42, 3], text = sprintf("<b>%s</b>", cluster_annotations[42, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[43, 1], y = cluster_annotations[43, 2], z = cluster_annotations[43, 3], text = sprintf("<b>%s</b>", cluster_annotations[43, 4]), font = list(size = 11)), 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        list(showarrow = F, x = cluster_annotations[44, 1], y = cluster_annotations[44, 2], z = cluster_annotations[44, 3], text = sprintf("<b>%s</b>", cluster_annotations[44, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[45, 1], y = cluster_annotations[45, 2], z = cluster_annotations[45, 3], text = sprintf("<b>%s</b>", cluster_annotations[45, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[46, 1], y = cluster_annotations[46, 2], z = cluster_annotations[46, 3], text = sprintf("<b>%s</b>", cluster_annotations[46, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[47, 1], y = cluster_annotations[47, 2], z = cluster_annotations[47, 3], text = sprintf("<b>%s</b>", cluster_annotations[47, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[48, 1], y = cluster_annotations[48, 2], z = cluster_annotations[48, 3], text = sprintf("<b>%s</b>", cluster_annotations[48, 4]), font = list(size = 11)), 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        list(showarrow = F, x = cluster_annotations[49, 1], y = cluster_annotations[49, 2], z = cluster_annotations[49, 3], text = sprintf("<b>%s</b>", cluster_annotations[49, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[50, 1], y = cluster_annotations[50, 2], z = cluster_annotations[50, 3], text = sprintf("<b>%s</b>", cluster_annotations[50, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[51, 1], y = cluster_annotations[51, 2], z = cluster_annotations[51, 3], text = sprintf("<b>%s</b>", cluster_annotations[51, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[52, 1], y = cluster_annotations[52, 2], z = cluster_annotations[52, 3], text = sprintf("<b>%s</b>", cluster_annotations[52, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[53, 1], y = cluster_annotations[53, 2], z = cluster_annotations[53, 3], text = sprintf("<b>%s</b>", cluster_annotations[53, 4]), font = list(size = 11)), 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        list(showarrow = F, x = cluster_annotations[54, 1], y = cluster_annotations[54, 2], z = cluster_annotations[54, 3], text = sprintf("<b>%s</b>", cluster_annotations[54, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[55, 1], y = cluster_annotations[55, 2], z = cluster_annotations[55, 3], text = sprintf("<b>%s</b>", cluster_annotations[55, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[56, 1], y = cluster_annotations[56, 2], z = cluster_annotations[56, 3], text = sprintf("<b>%s</b>", cluster_annotations[56, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[57, 1], y = cluster_annotations[57, 2], z = cluster_annotations[57, 3], text = sprintf("<b>%s</b>", cluster_annotations[57, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[58, 1], y = cluster_annotations[58, 2], z = cluster_annotations[58, 3], text = sprintf("<b>%s</b>", cluster_annotations[58, 4]), font = list(size = 11)), 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        list(showarrow = F, x = cluster_annotations[59, 1], y = cluster_annotations[59, 2], z = cluster_annotations[59, 3], text = sprintf("<b>%s</b>", cluster_annotations[59, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[60, 1], y = cluster_annotations[60, 2], z = cluster_annotations[60, 3], text = sprintf("<b>%s</b>", cluster_annotations[60, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[61, 1], y = cluster_annotations[61, 2], z = cluster_annotations[61, 3], text = sprintf("<b>%s</b>", cluster_annotations[61, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[62, 1], y = cluster_annotations[62, 2], z = cluster_annotations[62, 3], text = sprintf("<b>%s</b>", cluster_annotations[62, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[63, 1], y = cluster_annotations[63, 2], z = cluster_annotations[63, 3], text = sprintf("<b>%s</b>", cluster_annotations[63, 4]), font = list(size = 11)), 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        list(showarrow = F, x = cluster_annotations[64, 1], y = cluster_annotations[64, 2], z = cluster_annotations[64, 3], text = sprintf("<b>%s</b>", cluster_annotations[64, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[65, 1], y = cluster_annotations[65, 2], z = cluster_annotations[65, 3], text = sprintf("<b>%s</b>", cluster_annotations[65, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[66, 1], y = cluster_annotations[66, 2], z = cluster_annotations[66, 3], text = sprintf("<b>%s</b>", cluster_annotations[66, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[67, 1], y = cluster_annotations[67, 2], z = cluster_annotations[67, 3], text = sprintf("<b>%s</b>", cluster_annotations[67, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[68, 1], y = cluster_annotations[68, 2], z = cluster_annotations[68, 3], text = sprintf("<b>%s</b>", cluster_annotations[68, 4]), font = list(size = 11)), 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        list(showarrow = F, x = cluster_annotations[69, 1], y = cluster_annotations[69, 2], z = cluster_annotations[69, 3], text = sprintf("<b>%s</b>", cluster_annotations[69, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[70, 1], y = cluster_annotations[70, 2], z = cluster_annotations[70, 3], text = sprintf("<b>%s</b>", cluster_annotations[70, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[71, 1], y = cluster_annotations[71, 2], z = cluster_annotations[71, 3], text = sprintf("<b>%s</b>", cluster_annotations[71, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[72, 1], y = cluster_annotations[72, 2], z = cluster_annotations[72, 3], text = sprintf("<b>%s</b>", cluster_annotations[72, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[73, 1], y = cluster_annotations[73, 2], z = cluster_annotations[73, 3], text = sprintf("<b>%s</b>", cluster_annotations[73, 4]), font = list(size = 11)), 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        list(showarrow = F, x = cluster_annotations[74, 1], y = cluster_annotations[74, 2], z = cluster_annotations[74, 3], text = sprintf("<b>%s</b>", cluster_annotations[74, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[75, 1], y = cluster_annotations[75, 2], z = cluster_annotations[75, 3], text = sprintf("<b>%s</b>", cluster_annotations[75, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[76, 1], y = cluster_annotations[76, 2], z = cluster_annotations[76, 3], text = sprintf("<b>%s</b>", cluster_annotations[76, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[77, 1], y = cluster_annotations[77, 2], z = cluster_annotations[77, 3], text = sprintf("<b>%s</b>", cluster_annotations[77, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[78, 1], y = cluster_annotations[78, 2], z = cluster_annotations[78, 3], text = sprintf("<b>%s</b>", cluster_annotations[78, 4]), font = list(size = 11)), 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        list(showarrow = F, x = cluster_annotations[79, 1], y = cluster_annotations[79, 2], z = cluster_annotations[79, 3], text = sprintf("<b>%s</b>", cluster_annotations[79, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[80, 1], y = cluster_annotations[80, 2], z = cluster_annotations[80, 3], text = sprintf("<b>%s</b>", cluster_annotations[80, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[81, 1], y = cluster_annotations[81, 2], z = cluster_annotations[81, 3], text = sprintf("<b>%s</b>", cluster_annotations[81, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[82, 1], y = cluster_annotations[82, 2], z = cluster_annotations[82, 3], text = sprintf("<b>%s</b>", cluster_annotations[82, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[83, 1], y = cluster_annotations[83, 2], z = cluster_annotations[83, 3], text = sprintf("<b>%s</b>", cluster_annotations[83, 4]), font = list(size = 11)), 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        list(showarrow = F, x = cluster_annotations[84, 1], y = cluster_annotations[84, 2], z = cluster_annotations[84, 3], text = sprintf("<b>%s</b>", cluster_annotations[84, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[85, 1], y = cluster_annotations[85, 2], z = cluster_annotations[85, 3], text = sprintf("<b>%s</b>", cluster_annotations[85, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[86, 1], y = cluster_annotations[86, 2], z = cluster_annotations[86, 3], text = sprintf("<b>%s</b>", cluster_annotations[86, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[87, 1], y = cluster_annotations[87, 2], z = cluster_annotations[87, 3], text = sprintf("<b>%s</b>", cluster_annotations[87, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[88, 1], y = cluster_annotations[88, 2], z = cluster_annotations[88, 3], text = sprintf("<b>%s</b>", cluster_annotations[88, 4]), font = list(size = 11)), 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        list(showarrow = F, x = cluster_annotations[89, 1], y = cluster_annotations[89, 2], z = cluster_annotations[89, 3], text = sprintf("<b>%s</b>", cluster_annotations[89, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[90, 1], y = cluster_annotations[90, 2], z = cluster_annotations[90, 3], text = sprintf("<b>%s</b>", cluster_annotations[90, 4]), font = list(size = 11)), list(showarrow = F, x = cluster_annotations[91, 1], y = cluster_annotations[91, 2], z = cluster_annotations[91, 3], text = sprintf("<b>%s</b>", cluster_annotations[91, 4]), font = list(size = 11)))))

p
```
