#' Generate a 3-D t-SNE plot
#'
#' \code{plotSNE} generates a 3-D plot given the data generated by Rtsne
#' 
#' @param sample the sample for which the plot has to be generated
#' @param output_file will be \code{sampleID}.html if not set
#' @param output_dir will be current directory if not set
#' @export
#' @import plotly

plotSNE <- function(sampleID=1,output_file=NULL,output_dir=getwd(),pipeline=NULL,version=NULL,...){
  if(is.null(output_file)) output_file <- paste0(sampleID,".pdf")
  report <- file.path(output_dir, "tSNE.Rmd")
  rmarkdown::render(report, output_dir=output_dir, output_file=output_file, intermediates_dir=output_dir, knit_root_dir=output_dir, params=list(sampleID=sampleID,pipeline=pipeline,out_path=output_dir),...)
}
